# Generated by Django 4.2.7 on 2023-12-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menupage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_pic', models.ImageField(upload_to='menu_picture')),
                ('breakfast_name', models.CharField(max_length=100)),
                ('breakfast_info', models.CharField(max_length=255)),
                ('breakfast_price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
