# Generated by Django 4.2.7 on 2023-12-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menupage', '0002_breakfastmenu_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanchMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lanch_pic', models.ImageField(upload_to='menu_picture')),
                ('Lanch_name', models.CharField(max_length=100)),
                ('Lanch_info', models.CharField(max_length=255)),
                ('Lanch_price', models.IntegerField()),
            ],
        ),
    ]
