# Generated by Django 4.2.7 on 2023-12-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menupage', '0004_rename_lanch_info_lanchmenu_lanch_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_pic', models.ImageField(upload_to='menu_picture')),
                ('dinner_name', models.CharField(max_length=100)),
                ('dinner_info', models.CharField(max_length=255)),
                ('dinner_price', models.IntegerField()),
            ],
        ),
    ]
