# Generated by Django 4.2.7 on 2023-12-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
