# Generated by Django 4.2.7 on 2023-12-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_pic', models.ImageField(upload_to='Team_picture')),
                ('team_name', models.CharField(max_length=100)),
                ('team_info', models.CharField(max_length=100)),
                ('team_time', models.CharField(max_length=100)),
            ],
        ),
    ]
