# Generated by Django 4.2.7 on 2023-12-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestiMonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_pic', models.ImageField(upload_to='Testimonial_picture')),
                ('testimonial_name', models.CharField(max_length=100)),
                ('testimonial_about', models.CharField(max_length=100)),
                ('testimonial_dis', models.TextField()),
            ],
        ),
    ]
