# Generated by Django 4.2.7 on 2023-12-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costomername', models.CharField(max_length=200)),
                ('costomeremail', models.EmailField(max_length=100, unique=True)),
                ('DateTime', models.DateTimeField()),
                ('totalpeople', models.IntegerField()),
                ('special_request', models.TextField()),
            ],
        ),
    ]
