# Generated by Django 4.2.7 on 2023-12-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutpage', '0002_aboutteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutteam',
            name='about_time',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
