# Generated by Django 4.2.7 on 2023-12-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('useremail', models.EmailField(blank=True, max_length=70, unique=True)),
                ('usersubject', models.CharField(max_length=255)),
                ('usermessage', models.TextField()),
            ],
        ),
    ]
